import React from "react";
import {
  ArrowLeft,
  AlertTriangle,
  Stethoscope,
  ShieldCheck
} from "lucide-react";

import { Link } from "react-router-dom";

import "../styles/legal.css";

function Disclaimer() {
  return (
    <div className="legal-page">

      <div className="legal-container">

        <Link to="/" className="back-home">
          <ArrowLeft size={18} />
          Back to Home
        </Link>


        <div className="legal-header">

          <div className="legal-icon warning">
            <AlertTriangle size={30} />
          </div>

          <h1>Medical Disclaimer</h1>

          <p>
            Important information about SkinAI analysis results.
          </p>

        </div>


        <div className="legal-card">

          <div className="medical-warning">

            <AlertTriangle size={28} />

            <div>

              <h3>
                SkinAI Does Not Provide a Medical Diagnosis
              </h3>

              <p>
                The results generated by SkinAI are intended for
                educational and informational purposes only.
              </p>

            </div>

          </div>


          <h2>1. AI-Assisted Analysis</h2>

          <p>
            SkinAI analyzes visual patterns in uploaded images using
            artificial intelligence. The result represents an
            AI-assisted prediction and should not be interpreted as
            a confirmed diagnosis.
          </p>


          <h2>2. Accuracy</h2>

          <p>
            AI-generated results may be affected by image quality,
            lighting, camera characteristics, skin appearance, and
            other factors. Therefore, results may not always be
            accurate.
          </p>


          <h2>3. Professional Medical Advice</h2>

          <p>
            If you have concerns about a skin condition, consult a
            qualified dermatologist or other appropriate healthcare
            professional.
          </p>


          <h2>4. Do Not Delay Medical Care</h2>

          <p>
            Do not delay, avoid, or discontinue professional medical
            care based solely on information provided by SkinAI.
          </p>


          <h2>5. Emergency Situations</h2>

          <p>
            If you experience a serious or rapidly worsening medical
            condition, seek appropriate emergency medical assistance
            instead of relying on SkinAI.
          </p>


          <div className="doctor-card">

            <Stethoscope size={30} />

            <div>

              <h3>
                Consult a Healthcare Professional
              </h3>

              <p>
                Only a qualified healthcare professional can provide
                an appropriate medical evaluation and diagnosis.
              </p>

            </div>

          </div>


          <div className="legal-notice">

            <ShieldCheck size={22} />

            <span>
              SkinAI is an educational AI-assisted tool and should
              not replace professional medical diagnosis or treatment.
            </span>

          </div>

        </div>

      </div>

    </div>
  );
}

export default Disclaimer;